---
apiVersion: v1
kind: Secret
metadata:
  name: cedricclyburn-1-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-gh/cedricclyburn-1-gateway-gitops
